### ISSUE TITLE
Migration list from Slack Stream

### ISSUE THREAD

**Issue by KongariBug** [mazun/ASlack-Stream#10]
- [x] right click menu
- [x] edit mode
- [x] display file share messages
- [x] keyboard shortcut
- [x] autocomplete user name
- [x] markdown

**Comment by soramichi** [comment]
- [ ] auto-complete for original emojis of each channel
- [ ] fancy README and screen shots
- [ ] use of im.list API (https://slack.com/api/im.list) to handle DMs

**Comment by mazun** [comment]
right click menu will be replaced by setting page.

**Comment by mazun** [comment]
keyboard shortcut is implemented in #14 #13
