### ISSUE TITLE
We need an icon.

### ISSUE THREAD

**Issue by KongariBug** [mazun/ASlack-Stream#36]
ASAP

**Comment by mazun** [comment]
I decided to use this icon temporary.
If you have any idea of icon, please tell me.
This icon is applied to only windows currently.

<img width="512" alt="ss" src="https://user-images.githubusercontent.com/792477/26944438-a478a6a2-4cc3-11e7-9b6c-0d30ede03f1e.png">

**Comment by mazun** [comment]
It works all supported platforms.
