### ISSUE TITLE
Multiple Connection

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#39]
When the setting window is opened and closed (by clicking the save button) with a short interval, ASS mistakenly connects to one team with more than 2 rtm clients, which causes message duplication as in the screenshot.

It looks like something goes wrong when a rtm client is closed before its start() method has finished.

![dup](https://user-images.githubusercontent.com/11990836/26931626-1df14e4e-4c9c-11e7-9a99-79fa4ba94eb7.png)

**Comment by mazun** [comment]
We will move responsibility of receiving events from component to service.
It will resolve this issue.
