### ISSUE TITLE
Incremental Update

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#46]
Currently the released zip files are around 50 MB large and we need to provide archives that include only the diffs from the last release.

It seems like the diffs between releases are only in the `resource/app` directory, and it can be compressed into just 2.2 MB of a zip file.

**Comment by mazun** [comment]
Does the content in `resource/app` differ by platform?

**Comment by soramichi** [comment]
The contents  of these directories are completely the same:

```
aslack-stream-win32-x64/resources/app
aslack-stream-linux-x64/resources/app
aslack-stream-darwin-x64/aslack-stream.app/Contents/Resources/app
```

**Comment by mazun** [comment]
Thanks. We will add the link to download only app directory.

**Comment by mazun** [comment]
Done
http://1341shangrila.dip.jp/aslackstream/build/index.html
