### ISSUE TITLE
Reaction to an image thumbnail not shown in ASS

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#54]
Reactions added to an image thumbnail do not appear in ASS

**Comment by mazun** [comment]
![2017-06-12 20 48 44](https://user-images.githubusercontent.com/792477/27032600-9a99a02e-4fb0-11e7-86a2-a0654cb696f3.png)
![2017-06-12 20 49 46](https://user-images.githubusercontent.com/792477/27032621-b250b9aa-4fb0-11e7-9196-8d1a8f737e49.png)
