### ISSUE TITLE
Icon gets rough when enlarged and smallened

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#59]
We need a vectorized version?

![image](https://user-images.githubusercontent.com/11990836/27060268-9e5bead0-5016-11e7-8558-e5e599904a77.png)

**Comment by soramichi** [comment]
Improved by #80.

Maybe the .ico file should include icons of multiple sizes to be shown clearly in an arbitrary size, but close it for now as it might be trouble some to implement.

**Comment by mazun** [comment]
Note that the commit improve this issue is https://github.com/mazun/ASlack-Stream/commit/51b777c67130dac1e91b9c49a8c08b4f491cfc84
