### ISSUE TITLE
Mark read does not work for DMs and private channels

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#7]
Because DMs and private channels are treated as different things from normal channels, the current implementation of `mark_read` that uses `message.channelID` does not work for DMs and private channels.

```
Unhandled Promise rejection: channel_not_found ; Zone: <root> ; Task: Promise.then ; Value: Error: channel_not_found
...
...
```

**Comment by mazun** [comment]
It works by these commits; https://github.com/mazun/ASlack-Stream/commit/9b2da7b3df47b729d0cc99c4244f361360727e73, https://github.com/mazun/ASlack-Stream/commit/7bcf881a64ea2ba277aa1479eaaec1275d16405a
