### ISSUE TITLE
Muting many channels breaks the bottom bar

### ISSUE THREAD

**Issue by soramichi** [mazun/ASlack-Stream#84]
Because the height of the bottom bar is fixed, muting many channels at one time makes it broken and the setting button gets completely hidden.

Muting four channels: two are shown but the other two and the setting button are outside of the window.
![image](https://user-images.githubusercontent.com/11990836/27250061-df6cf752-535f-11e7-9244-76264c7a0843.png)

Changing the `height` attribute of the `.menus` class into `min-height`: better, but not quite perfect :disappointed: 
![image](https://user-images.githubusercontent.com/11990836/27250093-3c3c0a04-5360-11e7-9e35-ade2f5bf6ce8.png)

**Comment by KongariBug** [comment]
i try
